import { EmergencyContext } from '../types/context';

export interface DemoScenarioInfo {
  id: string;
  title: string;
  subtitle: string;
  category: 'Hospital' | 'Safety' | 'Low Confidence Demo' | 'Accident';
  badge: string;
  expectedConfidence: 'high' | 'medium' | 'low';
  intents: string[];
  context: EmergencyContext;
}

export const DEMO_SCENARIOS: DemoScenarioInfo[] = [
  {
    id: 'hospital_pitch_demo',
    title: 'Hospital Emergency: Wife Fall & Head Injury',
    subtitle: 'Primary 2-Minute Pitch Demonstration with doctor two-way exchange',
    category: 'Hospital',
    badge: 'Flagship Pitch Demo',
    expectedConfidence: 'high',
    intents: ['WIFE', 'FALL', 'HEAD_INJURY', 'UNCONSCIOUS', 'BREATHING_PROBLEM'],
    context: {
      id: 'CTX-1042',
      person: 'Wife',
      incident: 'Fall from stairs at home',
      injuries: ['Head impact with swelling'],
      consciousness: 'Unconscious',
      symptoms: ['Difficulty breathing / Gasping'],
      duration: '15 minutes ago',
      knownConditions: ['Diabetes Type 2'],
      allergies: ['Penicillin'],
      medications: ['Metformin 500mg'],
      immediateRequest: 'Immediate trauma triage and resuscitation',
      confirmedByUser: true,
      confidenceTier: 'high',
      confidenceScore: 94,
      criticalFlag: true,
      timestamp: '10:42 AM',
      updatedAt: '10:43 AM',
    },
  },
  {
    id: 'breathing_problem',
    title: 'Acute Respiratory Distress',
    subtitle: 'User signing severe asthma / shortness of breath',
    category: 'Hospital',
    badge: 'High Confidence Flow',
    expectedConfidence: 'high',
    intents: ['SELF', 'BREATHING_PROBLEM', 'EMERGENCY'],
    context: {
      id: 'CTX-1043',
      person: 'Self',
      incident: 'Sudden onset asthma exacerbation',
      injuries: [],
      consciousness: 'Conscious',
      symptoms: ['Severe shortness of breath', 'Wheezing', 'Chest tightness'],
      duration: '30 minutes ago',
      knownConditions: ['Bronchial Asthma'],
      allergies: ['Dust / Pollen'],
      medications: ['Salbutamol Inhaler (out of reach)'],
      immediateRequest: 'Nebulization & oxygen support',
      confirmedByUser: true,
      confidenceTier: 'high',
      confidenceScore: 92,
      criticalFlag: true,
      timestamp: '11:15 AM',
      updatedAt: '11:16 AM',
    },
  },
  {
    id: 'chest_pain_medium_conf',
    title: 'Chest Pain (Medium Confidence Clarification)',
    subtitle: 'Demonstrates ambiguity detection and user clarification chips',
    category: 'Safety',
    badge: 'Ambiguity Disambiguation',
    expectedConfidence: 'medium',
    intents: ['CHEST_PAIN', 'PAIN'],
    context: {
      id: 'CTX-1044',
      person: 'Self',
      incident: 'Sudden retrosternal pressure',
      injuries: [],
      consciousness: 'Conscious',
      symptoms: ['Heavy retrosternal chest pressure radiating to left arm'],
      duration: '45 minutes ago',
      knownConditions: ['Hypertension'],
      allergies: [],
      medications: ['Amlodipine 5mg'],
      immediateRequest: 'Immediate ECG and cardiac evaluation',
      confirmedByUser: false,
      confidenceTier: 'medium',
      confidenceScore: 74,
      criticalFlag: true,
      timestamp: '11:30 AM',
      updatedAt: '11:31 AM',
    },
  },
  {
    id: 'bleeding_low_conf',
    title: 'Bleeding / Occluded Visual (Low Confidence Fallback)',
    subtitle: 'Demonstrates "Know when you don\'t know" & instant interpreter escalation',
    category: 'Low Confidence Demo',
    badge: 'Safety Fail-Safe',
    expectedConfidence: 'low',
    intents: ['BLEEDING'],
    context: {
      id: 'CTX-1045',
      person: 'Self',
      incident: 'Laceration / Bleeding',
      injuries: ['Active bleeding from forearm'],
      consciousness: 'Conscious',
      symptoms: ['Deep cut, active bleeding'],
      duration: '5 minutes ago',
      knownConditions: [],
      allergies: [],
      medications: [],
      immediateRequest: 'Wound dressing & surgical review',
      confirmedByUser: false,
      confidenceTier: 'low',
      confidenceScore: 38,
      criticalFlag: true,
      timestamp: '11:45 AM',
      updatedAt: '11:45 AM',
    },
  },
  {
    id: 'call_ambulance',
    title: 'Road Accident & Ambulance Request',
    subtitle: 'Multi-party collision with trauma emergency call',
    category: 'Accident',
    badge: 'Rapid Dispatch',
    expectedConfidence: 'high',
    intents: ['ACCIDENT', 'CALL_AMBULANCE', 'HELP'],
    context: {
      id: 'CTX-1046',
      person: 'Co-passenger',
      incident: 'Two-wheeler road collision',
      injuries: ['Leg fracture suspected', 'Road abrasions'],
      consciousness: 'Conscious',
      symptoms: ['Inability to bear weight, intense pain'],
      duration: 'Just now',
      knownConditions: [],
      allergies: [],
      medications: [],
      immediateRequest: 'Emergency ambulance with stretcher dispatch',
      confirmedByUser: true,
      confidenceTier: 'high',
      confidenceScore: 96,
      criticalFlag: true,
      timestamp: '12:04 PM',
      updatedAt: '12:05 PM',
    },
  },
];
